# Generated by Django 2.2.6 on 2019-11-03 02:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
