# Generated by Django 2.2.6 on 2019-11-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0002_auto_20191103_0253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
            ],
        ),
    ]
